{% set version = "0.10.2" %}
{% set sha256 = "1e5b49cd1446ce2846b99354924ac71513210bb07c87f862fe83d17d290adc25" %}

package:
    name: bqplot
    version: {{ version }}

source:
    fn: bqplot-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
    sha256: {{ sha256  }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=7.0.0,<8.0
        - traitlets >=4.3.0,<5.0
        - traittypes >=0.0.6
        - numpy >=1.10.4
        - pandas

test:
    imports:
        - bqplot

about:
    home: https://github.com/bloomberg/bqplot
    license: Apache 2.0
    summary: Plotting library for Jupyter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
