{% set version = "0.8.4" %}
{% set sha256 = "a0a79d08269b0805330ad192234206452504db87ceeeacdbfafed8c5e4c8e6e9" %}

package:
    name: bqplot
    version: {{ version }}

source:
    fn: bqplot-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
    sha256: {{ sha256  }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=5.2.2
        - traitlets >=4.3.0
        - traittypes >=0.0.6
        - numpy >=1.10.4
        - pandas

test:
    imports:
        - bqplot

about:
    home: https://github.com/bloomberg/bqplot
    license: Apache License 2.0
    summary: Plotting library for Jupyter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
