{% set version = "0.12.16" %}
{% set sha256 = "b3ea0a6a54211389c198d7c256e9bef56b47a227818631469ba6b95311e53303" %}

package:
  name: bqplot
  version: {{ version }}

source:
  fn: bqplot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - jupyter
    - pip
  run:
    - python
    - ipywidgets >=7.5.0,<8.0
    - traitlets >=4.3.0,<5.0
    - traittypes >=0.0.6
    - numpy >=1.10.4
    - pandas

test:
  imports:
    - bqplot

about:
  home: https://github.com/bloomberg/bqplot
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Plotting library for Jupyter
  description: Plotting library for Jupyter
  doc_url: https://bqplot.readthedocs.io
  dev_url: https://github.com/bloomberg/bqplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
    - ChakriCherukuri
    - ibdafna
    - martinRenou
    - kaiayoung
