{% set version = "0.11.2" %}
{% set sha256 = "ee9f59b1eaa1871afe8fc1a8fe4c57d12ffe05f4a8b55cd6ac6804cd1259245d" %}

package:
    name: bqplot
    version: {{ version }}

source:
    fn: bqplot-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
    sha256: {{ sha256  }}

build:
    number: 1000
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    host:
        - python
        - setuptools
        - jupyter
        - pip
    run:
        - python
        - ipywidgets >=7.0.0,<8.0
        - traitlets >=4.3.0,<5.0
        - traittypes >=0.0.6
        - numpy >=1.10.4
        - pandas

test:
    imports:
        - bqplot

about:
    home: https://github.com/bloomberg/bqplot
    license: Apache 2.0
    summary: Plotting library for Jupyter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
