{% set version = "0.8.2" %}

package:
    name: bqplot
    version: {{ version }}

source:
    fn: bqplot-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
    md5: 17ab8e10bb36b95b192ea1848215efc9

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=5.2.2
        - numpy >=1.10.4
        - pandas
        # Pinning pyzmq because the current conda-forge pyzmq package does
        # not work with win+py35
        - pyzmq >=15.2.0

test:
    imports:
        - bqplot

about:
    home: https://github.com/bloomberg/bqplot
    license: Apache License 2.0
    summary: Plotting library for Jupyter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
