{% set version = "0.12.22" %}
{% set sha256 = "3f0eee5e2b03866f729ef295f9f46310dcafa832040064f40995a3e876986855" %}

package:
  name: bqplot
  version: {{ version }}

source:
  fn: bqplot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python  >=3.6
    - setuptools
    - jupyter
    - jupyter-packaging >=0.7.9
    - pip
  run:
    - python  >=3.6
    - ipywidgets >=7.6.0,<8.0
    - traitlets >=4.3.0,<6.0
    - traittypes >=0.0.6
    - numpy >=1.10.4
    - pandas

test:
  imports:
    - bqplot
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/bqplot/extension.js                                       # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/bqplot/index.js                                           # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/bqplot/package.json                                      # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\bqplot\\extension.js (exit 0) else (exit 1)           # [win]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\bqplot\\index.js (exit 0) else (exit 1)               # [win]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\bqplot\\package.json (exit 0) else (exit 1)          # [win]

about:
  home: https://github.com/bloomberg/bqplot
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Plotting library for Jupyter
  description: Plotting library for Jupyter
  doc_url: https://bqplot.readthedocs.io
  dev_url: https://github.com/bloomberg/bqplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
    - ChakriCherukuri
    - ibdafna
    - martinRenou
    - kaiayoung
