travis:
  secure:
    BINSTAR_TOKEN: HN/lMZi27iu7y7fOvjs24Wh5Mps+m7zroaAV8FP8woGFy145TiSdWP6SOOuOY8q8PBwuPMWfvl2qmZL8oKZnqIH9nyp2P1xpLsjLeSeNjDfQnr3xlyeB2CbFB+prYR/BORGS/WhGEYQ3S3U8Y/BOlAhjgFkhBByf/pFzYfBixgNTv39o4X9iwnYG/DjB3hYjsUK7E+vzAhLMCpvXXA03wlzijxra0/vVhrpqG3Ac155XqYMFCbWz0QlDSg4QVBdcCWRkUN3QZYtoP75PyZC5oVG0hqf58ciwmz2nkxUzxB9dFG40vUTniXH0E3B0SRk+yH1UyXCPyfHZhuJHtWYPjMUyiIQ4KC7HfBxl92vTtf0wlj/VyMIAqm9K4ceLbwq3kxww1wnFuj7bgnrybdvfzGRgFZTFC6YZeBk6Qdwu7OM1EM7i9xK+Unt8CK+n8OisjHD7l04iYjAdrLt3Ug9q/ogDBKwGz+/lBprVaquTrSpmULV16LM4gH3CrInpPnhqZWaNrt73zA7wXuE1CwYCUaOYyBvD604OdTnxX7L4t19rycy6suQY+qmY1/SuUGDRUl3acIWtL99mBHthPKDgHzOrZA+ku3NVc4ttz05ajr09S7/N3D97W6m1UJoToNK6W3EGP0MXZNaBKZDaVVRQYZ7Zq0n332KTdmIbOWITElA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
