travis:
  secure:
    BINSTAR_TOKEN: iwE38Rz3e0r4llI3u1z7UNPx5WscNdNu2qe2kVTuX+0Gr0vQbSq7yOfQHzB72T07vq25wb0XXkhLJ9YzrGcy6f9NkSG6ekLxV2BsRH1z+cNdbWv+DnH2SWmCbMsjRuJoGzhvh9YOKLT5HHpVwNT941jkkYyXZ5B13bt/BU4IM8ybtIr48bchyS+TARxAGJuVO4TD2zlJFETEh1gU81X6aRZ7DJb4vRIjYXPIthu73iDXir/6uniB8Ey2oG54Y+2p5kjP3Vbbns752HVO97JbJmFijclxYXhwXdXphRGfkbo4hekE2QJmphzV0VZd0ZmnNlabkm00u+PiZPUNm4y2EGAQKvmc3XEsAQO2GjphJVTqNK2Dcgiv3e5yJ8tv1zwkCmWgKfX/nyp1fAwLeWQn4GBDOB1aIlD5n0xXWqlIk7ZHN/9t8pOD6KLPHVFdmXFyG0Rnh/NWIeMtw59UT9sq1Yxw3pG68jfZ2s4wNZn0PhwbDMtl/y46C2wT9so6yKoXUVzS48bEhJQjiIawhujqMG2ejwmAd5xUOPt7OcU45AHLQEYpMauMFOjx2niVvytK+gol1gppxlDYQ6csDJFHdWuIOoVRxS5OzQK1W0fB7eXKmBQiyhx38BlA0vFHS83vwu8XFf919rCGuAUZ4YIC6XuCZjtRONCl0r7Z8f92zNA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
